# Shazia Patel
# 6/20/2024
# P1HW1
# Calclating Exponent, Addition and Substraction.
print()
print()
print("-----Calculating Exponents----")
print()
print()
integer1 = int(input("Enter an integer as the base value: "))
integer2 = int(input("Enter an integer as the exponent: "))
print()
print()
print(integer1, "raise to the power of", integer2 , 'is', integer1**integer2, "!!")
print()
print()
print("-----Addition and Subtraction----")
print()
print()
integer3 = int(input("Enter a starting integer: "))
integer4 = int(input("Enter an integer to add: "))
integer5 = int(input("Enter an integer to subtract: "))
print()
print()
print(integer3,"+",integer4,"-",integer5, "is equal to ",integer3+integer4-integer5)
